#!/usr/bin/env bash
#
# restore_helper.sh
# Helper to simplify restores from local backup or rclone remote.
# Place in /home/ubuntu/cleanup/ and run with sudo.
#
# Examples:
#  # Restore all files listed by a run from remote:
#  sudo /home/ubuntu/cleanup/restore_helper.sh --from remote --run /home/ubuntu/cleanup/runs/run_20251223_232206
#
#  # Restore only company 1 files from remote for that run:
#  sudo /home/ubuntu/cleanup/restore_helper.sh --from remote --run /home/ubuntu/cleanup/runs/run_20251223_232206 --company 1
#
#  # Restore single file from remote:
#  sudo /home/ubuntu/cleanup/restore_helper.sh --from remote --run /home/ubuntu/cleanup/runs/run_20251223_232206 --file "2/416/28/Yvx4NCwMLp/vendas ernesto.xls"
#
#  # Restore single file from local backup:
#  sudo /home/ubuntu/cleanup/restore_helper.sh --from backup --backup-dir /var/backups/media/media_backup_20251223_183810 --file "1/374/8/TCsKn-1765832675438.jpeg"
#
set -euo pipefail

# Defaults - adjust if necessary
HOME_BASE="/home/ubuntu/cleanup"
MEDIA_ROOT="/var/lib/docker/volumes/ticketz-docker-acme_backend_public/_data"
RCLONE_CONFIG="/home/ubuntu/.config/rclone/rclone.conf"
DEFAULT_RCLONE_REMOTE="cleanup:cleanup/media"
TMP_ROOT="${HOME_BASE}/tmp_restore"

usage() {
  cat <<EOF
Usage: sudo restore_helper.sh --from <backup|remote> [options]

Options:
  --from <backup|remote>        source to restore from (required)
  --run /path/to/run_dir        run dir generated by cleanup_media_manager (uses media_ticket_candidates.txt)
  --backup-dir /path/to/backup  backup dir (when --from backup) (optional)
  --remote <rclone_remote>      rclone remote (default: ${DEFAULT_RCLONE_REMOTE})
  --company 1|2                 restore only paths beginning with "1/" or "2/"
  --file "relpath"              restore single file (relative path under media/)
  --dry-run                     show actions without moving files into place
  --help                        show this help
Examples:
  sudo ${0} --from remote --run /home/ubuntu/cleanup/runs/run_20251223_232206
  sudo ${0} --from remote --run /home/ubuntu/cleanup/runs/run_20251223_232206 --company 1
  sudo ${0} --from backup --backup-dir /var/backups/media/media_backup_20251223_183810 --file "1/374/8/1765832675438.jpeg"
EOF
}

# Parse args
FROM=""
RUN_DIR=""
BACKUP_DIR=""
RCLONE_REMOTE="${DEFAULT_RCLONE_REMOTE}"
COMPANY=""
SINGLE_FILE=""
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from) FROM="$2"; shift 2;;
    --run) RUN_DIR="$2"; shift 2;;
    --backup-dir) BACKUP_DIR="$2"; shift 2;;
    --remote|--rclone-remote) RCLONE_REMOTE="$2"; shift 2;;
    --company) COMPANY="$2"; shift 2;;
    --file) SINGLE_FILE="$2"; shift 2;;
    --dry-run) DRY_RUN=1; shift;;
    --help) usage; exit 0;;
    *) echo "Unknown arg: $1"; usage; exit 1;;
  esac
done

if [[ -z "${FROM}" ]]; then
  echo "Error: --from is required (backup|remote)"; usage; exit 1
fi

# Helpers
log() { echo "[$(date +'%F %T')] $*"; }
ensure_tmp() { sudo mkdir -p "${TMP_ROOT}"; sudo chown "$(whoami)" "${TMP_ROOT}"; }

# Build a files-from list according to inputs
build_list() {
  local out="$1"
  if [[ -n "${SINGLE_FILE}" ]]; then
    printf '%s\n' "${SINGLE_FILE}" > "${out}"
    return 0
  fi
  if [[ -n "${RUN_DIR}" ]]; then
    if [[ ! -f "${RUN_DIR}/media_ticket_candidates.txt" ]]; then
      echo "Run dir ${RUN_DIR} missing media_ticket_candidates.txt"; exit 1
    fi
    if [[ -n "${COMPANY}" ]]; then
      grep -E "^${COMPANY}/" "${RUN_DIR}/media_ticket_candidates.txt" > "${out}"
    else
      cp "${RUN_DIR}/media_ticket_candidates.txt" "${out}"
    fi
    return 0
  fi
  echo "Either --file or --run must be provided"; exit 1
}

# Restore functions
restore_from_backup() {
  local listfile="$1" backup_dir="$2"
  if [[ -z "${backup_dir}" ]]; then
    echo "backup-dir required for restore-from-backup"; exit 1
  fi
  log "Restoring from backup: ${backup_dir}"
  while IFS= read -r rel; do
    [[ -z "${rel}" ]] && continue
    src="${backup_dir}/${rel}"
    dst="${MEDIA_ROOT}/media/${rel}"
    if [[ ! -f "${src}" ]]; then
      echo "WARN: source missing in backup: ${src}"
      continue
    fi
    if [[ "${DRY_RUN}" -eq 1 ]]; then
      echo "DRY RUN: would copy ${src} -> ${dst}"
    else
      sudo mkdir -p "$(dirname "${dst}")"
      sudo cp -v -- "${src}" "${dst}"
      sudo chown root:root "${dst}" || true
      sudo chmod 644 "${dst}" || true
    fi
  done < "${listfile}"
}

restore_from_remote() {
  local listfile="$1" remote="$2"
  ensure_tmp
  local tmpdir
  tmpdir="$(mktemp -d "${TMP_ROOT}/restore_XXXX")"
  log "Will copy listed files from ${remote} into ${tmpdir} (using --files-from ${listfile})"
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    sudo rclone --config "${RCLONE_CONFIG}" copy "${remote}" "${tmpdir}" --files-from "${listfile}" --dry-run --progress
    log "DRY RUN finished"
    sudo rm -rf "${tmpdir}"
    return 0
  fi
  sudo rclone --config "${RCLONE_CONFIG}" copy "${remote}" "${tmpdir}" --files-from "${listfile}" --progress --log-file "${RUN_DIR:-${HOME_BASE}}/rclone_restore.log" --log-level INFO
  # move into media
  while IFS= read -r rel; do
    [[ -z "${rel}" ]] && continue
    src="${tmpdir}/${rel}"
    dst="${MEDIA_ROOT}/media/${rel}"
    if [[ ! -f "${src}" ]]; then
      echo "WARN: not restored from remote (missing): ${rel}"
      continue
    fi
    sudo mkdir -p "$(dirname "${dst}")"
    sudo mv -v -- "${src}" "${dst}"
    sudo chown root:root "${dst}" || true
    sudo chmod 644 "${dst}" || true
  done < "${listfile}"
  sudo rm -rf "${tmpdir}"
  log "Restore-from-remote completed"
}

# Main
TMP_LIST="$(mktemp)"
trap 'rm -f "${TMP_LIST}"' EXIT

build_list "${TMP_LIST}"

case "${FROM}" in
  backup)
    restore_from_backup "${TMP_LIST}" "${BACKUP_DIR}"
    ;;
  remote)
    restore_from_remote "${TMP_LIST}" "${RCLONE_REMOTE}"
    ;;
  *)
    echo "Unknown --from value: ${FROM}"; exit 1;;
esac

log "Done."
